# Generated by Django 5.0.6 on 2026-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='run_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
