apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: p2p
  labels:
    app: fastapi
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
    - name: http
      port: 8001
      targetPort: 8001
